name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        cd $HOME
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
        chmod +x miniconda.sh
        bash miniconda.sh -b -p $HOME/miniconda
        export PATH="$HOME/miniconda/bin:$PATH"
        $HOME/miniconda/bin/conda install numpy scipy astropy pip keyring --yes
        cd $GITHUB_WORKSPACE
        $HOME/miniconda/bin/python setup.py sdist
    - name: Publish to Anaconda
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
      if: startsWith(github.event.ref, 'refs/tags')
      run: |
        alias python=$HOME/miniconda/bin/python
        alias pip=$HOME/miniconda/bin/pip
        $HOME/miniconda/bin/pip install twine
        $HOME/miniconda/bin/conda install conda-build --yes
        $HOME/miniconda/bin/conda install anaconda-client --yes
        $HOME/miniconda/bin/conda config --add channels mavensdc
        $HOME/miniconda/bin/conda-build --python 3.6 --output-folder . .
        $HOME/miniconda/bin/conda convert -p linux-32 linux-64/*.tar.bz2
        $HOME/miniconda/bin/conda convert -p win-32 linux-64/*.tar.bz2
        $HOME/miniconda/bin/conda convert -p osx-64 linux-64/*.tar.bz2
        $HOME/miniconda/bin/conda convert -p win-64 linux-64/*.tar.bz2
        $HOME/miniconda/bin/anaconda upload --label main linux-64/*.tar.bz2
        $HOME/miniconda/bin/anaconda upload --label main osx-64/*.tar.bz2
        $HOME/miniconda/bin/anaconda upload --label main win-64/*.tar.bz2
        $HOME/miniconda/bin/anaconda upload --label main win-32/*.tar.bz2
        $HOME/miniconda/bin/anaconda upload --label main linux-32/*.tar.bz2
        rm -r linux-64
        rm -r linux-32
        rm -r osx-64
        rm -r win-64
        rm -r win-32
        $HOME/miniconda/bin/conda-build --python 3.7 --output-folder . .
        $HOME/miniconda/bin/conda convert -p linux-32 linux-64/*.tar.bz2
        $HOME/miniconda/bin/conda convert -p win-32 linux-64/*.tar.bz2
        $HOME/miniconda/bin/conda convert -p osx-64 linux-64/*.tar.bz2
        $HOME/miniconda/bin/conda convert -p win-64 linux-64/*.tar.bz2
        $HOME/miniconda/bin/anaconda upload --label main linux-64/*.tar.bz2
        $HOME/miniconda/bin/anaconda upload --label main osx-64/*.tar.bz2
        $HOME/miniconda/bin/anaconda upload --label main win-64/*.tar.bz2
        $HOME/miniconda/bin/anaconda upload --label main win-32/*.tar.bz2
        $HOME/miniconda/bin/anaconda upload --label main linux-32/*.tar.bz2
        rm -r linux-64
        rm -r linux-32
        rm -r osx-64
        rm -r win-64
        rm -r win-32
        $HOME/miniconda/bin/conda-build --python 3.8 --output-folder . .
        $HOME/miniconda/bin/conda convert -p linux-32 linux-64/*.tar.bz2
        $HOME/miniconda/bin/conda convert -p win-32 linux-64/*.tar.bz2
        $HOME/miniconda/bin/conda convert -p osx-64 linux-64/*.tar.bz2
        $HOME/miniconda/bin/conda convert -p win-64 linux-64/*.tar.bz2
        $HOME/miniconda/bin/anaconda upload --label main linux-64/*.tar.bz2
        $HOME/miniconda/bin/anaconda upload --label main osx-64/*.tar.bz2
        $HOME/miniconda/bin/anaconda upload --label main win-64/*.tar.bz2
        $HOME/miniconda/bin/anaconda upload --label main win-32/*.tar.bz2
        $HOME/miniconda/bin/anaconda upload --label main linux-32/*.tar.bz2
        rm -r linux-64
        rm -r linux-32
        rm -r osx-64
        rm -r win-64
        rm -r win-32