name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        cd $HOME
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
        chmod +x miniconda.sh
        bash miniconda.sh -b -p $HOME/miniconda
        export PATH="$HOME/miniconda/bin:$PATH"
        $HOME/miniconda/bin/conda install numpy scipy astropy xarray pip keyring --yes
        cd $GITHUB_WORKSPACE
        $HOME/miniconda/bin/python setup.py sdist
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@master
      if: startsWith(github.event.ref, 'refs/tags')
      with:
        password: ${{ secrets.pypi_password }}